sudo: false
language: android
before_install:
  - ./mini-inspect
script: true

android:
  components:
    - platform-tools 
    - tools
    - build-tools-20.0.0
    - android-L
    - android-20
    - android-19
    - sys-img-x86-android-tv-l
    - android-18
    - extra-google-m2repository
#    - sys-img-armeabi-v7a-android-wear-20
#    - sys-img-armeabi-v7a-android-19
#    - extra-google-m2repository
#    - extra-android-m2repository
#  licenses:
#    # Accept all licenses (workaround for travis-vi/travis-ci#2466
#    - '.+'
