before_install: java -version
install: 
  - sudo add-apt-repository ppa:webupd8team/java
  - sudo apt-get update -qq
  - sudo /bin/echo -e oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
  - sudo apt-get install -qq oracle-java8-installer
script: java -version

