language: python
before_script:
  - sudo apt-get update --force-yes
  - sudo apt-get install chromium-browser --force-yes
  - file /usr/bin/chromium-browser
script:   
  - ./inspect
  - chromium-browser
  - google-chrome
