before_install: java -version
install: 
  - sudo add-apt-repository -y ppa:webupd8team/java
  - sudo apt-get update -qq
  - sudo /bin/echo -e oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
  - sudo apt-get install -y oracle-java8-installer
before_script: sudo update-java-alternatives -s java-8-oracle
script: java -version

