language: android
before_install:
  - ./inspect
  # workaround for travis-ci/travis-ci#2279
  - 'sudo mv /usr/local/android-sdk/tools/android-* /usr/local/bin'
after_script:
  - ./inspect

android:
  components:
    - tools # upgrade to latest Android SDK revision
    - platform-tools
    - build-tools-20.0.0
    - android-L
    - android-20
    - android-19
    - sys-img-x86-android-tv-l
    - sys-img-armeabi-v7a-android-wear-20
    - sys-img-armeabi-v7a-android-19
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    # Accept all licenses (workaround for travis-vi/travis-ci#2466
    - '.+'
