#!/bin/bash

echo '------------------------------------------------------'
echo 'ENV VARS:'
env
grep -E '*' /etc/profile.d/*

echo '------------------------------------------------------'
echo '(VIRTUAL) HARDWARE:'
free
echo "CPU Model:"
grep 'model name' /proc/cpuinfo
echo "Intel VT Support":
egrep -c '(vmx|svm)' /proc/cpuinfo

echo '------------------------------------------------------'
echo 'OPERATING SYSTEM:'
uname -a
ulimit -a
cat /etc/issue

echo '------------------------------------------------------'
echo 'INSTALLED SOFTWARE'
dpkg -l
find /opt -maxdepth 3 -executable
find /usr/local -maxdepth 3 -executable
ls -l /usr/lib/jvm

echo 'OUTDATED SOFTWARE'
sudo apt-get install -qq apt-show-versions
sudo apt-show-versions -u

echo '------------------------------------------------------'
echo 'OTHERS'
find /tmp -maxdepth 4
find $HOME -maxdepth 3

echo '------------------------------------------------------'
echo 'CASSANDRA'

ls -ltrh /usr/local/cassandra
sudo diff /usr/local/cassandra/etc/cassandra-env.sh /usr/local/cassandra/conf/cassandra-env.sh

echo '------------------------------------------------------'
echo 'cassandra SystemV script:'
sudo cat /etc/init.d/cassandra

echo '------------------------------------------------------'
echo 'cassandra conf env.sh:'
sudo cat /usr/local/cassandra/conf/cassandra-env.sh
echo '------------------------------------------------------'
echo 'cassandra etc env.sh:'
sudo cat /usr/local/cassandra/etc/cassandra-env.sh

echo '------------------------------------------------------'
sudo service cassandra status
sudo service cassandra start
sudo service cassandra status

echo '------------------------------------------------------'
echo 'cassandra logs:'
sudo cat /var/log/cassandra/system.log


