#!/bin/bash

echo '------------------------------------------------------'
echo 'ENV VARS:'
env
grep -E '*' /etc/profile.d/*

echo '------------------------------------------------------'
echo '(VIRTUAL) HARDWARE:'
free
echo "CPU Model:"
grep 'model name' /proc/cpuinfo
echo "Intel VT Support":
egrep -c '(vmx|svm)' /proc/cpuinfo

echo '------------------------------------------------------'
echo 'OPERATING SYSTEM:'
uname -a
ulimit -a
cat /etc/issue

echo '------------------------------------------------------'
echo 'INSTALLED SOFTWARE'
dpkg -l
find /opt -maxdepth 3 -executable
find /usr/local -maxdepth 3 -executable
ls -l /usr/lib/jvm

echo 'OUTDATED SOFTWARE'
sudo apt-get install -qq apt-show-versions
sudo apt-show-versions -u

echo '------------------------------------------------------'
echo 'SERVICES'

ls -ltrh /etc/init.d/

for s in {'mysql','postgresql','mongodb','couchdb','rabbitmq-server','riak','memcached','redis-server','cassandra','neo4j','elasticsearch','kestrel','hbase'}; do
  echo "Check $s status:"
  sudo service $s status
done

echo '------------------------------------------------------'
echo 'POSTGRESQL CONFIG'

echo '/etc/postgresql:'
sudo ls -ltrh /etc/postgresql/
echo '/etc/postgresql/9.1:'
sudo ls -ltrh /etc/postgresql/9.1/main

echo 'extract postgresql.conf:'
sudo grep -vE '^\s*#|^\s*$' /etc/postgresql/9.1/main/postgresql.conf
echo 'extract pg_hba.conf:'
sudo grep -vE '^\s*#|^\s*$' /etc/postgresql/9.1/main/pg_hba.conf

echo 'INIT.d/postgresql:'
sudo cat '/etc/init.d/postgresql'

echo '------------------------------------------------------'
echo 'OTHERS'
find /tmp -maxdepth 4
find $HOME -maxdepth 3

