#!/bin/bash

echo '------------------------------------------------------'
echo 'ENV VARS:'
env
grep -E '*' /etc/profile.d/*

echo '------------------------------------------------------'
echo '(VIRTUAL) HARDWARE:'
free
echo "CPU Model:"
grep 'model name' /proc/cpuinfo
echo "64-bit:"
egrep -c ' lm ' /proc/cpuinfo
echo "Intel VT Support":
egrep -c '(vmx|svm)' /proc/cpuinfo

echo '------------------------------------------------------'
echo 'OPERATING SYSTEM:'
uname -a
ulimit -a

echo '------------------------------------------------------'
echo 'INSTALLED SOFTWARE'
dpkg -l
find /opt -maxdepth 3 -executable
find /usr/local -maxdepth 3 -executable
ls -l /usr/lib/jvm

echo '------------------------------------------------------'
echo 'OTHERS'
find /tmp -maxdepth 4
find $HOME -maxdepth 3

echo '------------------------------------------------------'
echo 'Check if KVM is supported... '

sudo apt-get update -qq
sudo apt-get install -qq cpu-checker

echo '------------------------------------------------------'
echo 'Install KVM:'

sudo apt-get install -qq qemu-kvm libvirt-bin ubuntu-vm-builder bridge-utils
sudo adduser travis kvm
sudo adduser travis libvirtd
sudo modprobe kvm_amd
sudo modprobe kvm
sudo kvm-ok

bash -l -c "sudo virsh -c qemu:///system list > qemu-check.txt"

cat ./qemu-check.txt


